baseURL = 'https://blig.blog/'
languageCode = 'en-gb'
title = 'Thought engineering'
theme = 'simple'

[params]
  description = 'A simple personal blog'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
